#PBS -l walltime=00:20:00
#PBS -l select=1:ncpus=48:mem=99GB

cd $PBS_O_WORKDIR

#DEBUG TEST SCRIPT FOR HPC
for filename in f_books; do
    for err in 4; do
        for no_threads in 4 6 8 10 12 14 16 18 20 22 24; do
            echo "$filename , $err , 4 , $no_threads";
            > parameters_flirt_mt.h;
            echo "#pragma once" >> parameters_flirt_mt.h;
            echo "#define NO_EXECUTION 50000000" >> parameters_flirt_mt.h;
            echo "#define ERROR $err" >> parameters_flirt_mt.h;
            echo "#define FANOUT 4" >> parameters_flirt_mt.h;
            echo "#define WINDOWSIZE 50000000" >> parameters_flirt_mt.h;
            echo "#define SEGMENT_LIMIT 1000000" >> parameters_flirt_mt.h;
            echo "#define NO_THREADS $no_threads" >> parameters_flirt_mt.h;
            g++ test_flirt_multithread.cpp -march=native -std=c++17 -O3 -pthread -w -o z_run_flirt_multi && ./z_run_flirt_multi $filename >> log_test.txt
done
done
done